### ISSUE TITLE
Rename TOTP section

### ISSUE THREAD

**Issue by rplopes** [uphold/docs#164]
The current title, "Time-Based One-Time Password (TOTP)", is getting truncated in the navigation sidebar:

<img width="245" alt="Screenshot 2019-03-11 at 16 51 22" src="https://user-images.githubusercontent.com/760760/54141613-ef3cf280-441d-11e9-8633-298f3cdde6d6.png">

Could we come up with a shorter title that won't get truncated?

**Comment by waldyrious** [comment]
It looks like only "One-Time Password" would fit:

<img width="247" alt="Screenshot 2019-03-12 at 09 47 56" src="https://user-images.githubusercontent.com/478237/54190598-0b877080-44ac-11e9-92a7-6b0b1dfe86df.png">
<img width="236" alt="Screenshot 2019-03-12 at 09 48 20" src="https://user-images.githubusercontent.com/478237/54190600-0c200700-44ac-11e9-8471-f37efc849f4d.png">

Would it be possible to provide a short title for the sidebar TOC without affecting the actual document title (so as to avoid losing precision)?
