### ISSUE TITLE
Expose all tickers

### ISSUE THREAD

**Issue by zamith** [uphold/docs#2]
Right now just some of the tickers are available for public consumption. It would be nice to get all of the combinations, especially when asking for the ticker to a specific currency.

Any plans for this?

Thanks.

**Comment by fixe** [comment]
Hi @zamith, this was already in the roadmap. I'll see if we can increase the priority, thanks.

**Comment by jrpereira** [comment]
Just as a sidenote, the ticker represents the price of 1 unit, but it does not account for market liquidity (eg, the 2nd unit might be available only at a different price). 

If the purpose is to promise a price to the user, the best option is to preview a transaction (create a transaction but don't commit), which also provides accurate fee information and is valid for at least 30 seconds.

**Comment by zamith** [comment]
@jrpereira Will do. Thanks.

**Comment by Americas** [comment]
This is a feature request for the API, not the API documentation.
