### ISSUE TITLE
Add support for filtering transaction list by type

### ISSUE THREAD

**Issue by byrnereese** [uphold/docs#68]
See: https://developer.bitreserve.org/en/community#!/bitreserve-developer/general%23list-card-issue-in-android

A developer has asked if we support retrieving a list of transactions that is filtered by type. This would be super helpful I think for a number of reasons. I wonder if implementing a new `search` endpoint would be a better approach? It might be more logical in some respects.

**Comment by fixe** [comment]
+1 for using query string for filtering resources.

Reference: http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#advanced-queries

**Comment by ruimarinho** [comment]
Another +1 for query string. The use case is interesting and expected too.

**Comment by rplopes** [comment]
Closing, as this seems to be related to product, not documentation.
